### ISSUE TITLE
Optional plugin still running while toggled off

### ISSUE THREAD

**Issue by derrickb** [pyblish/pyblish-lite#90] opened 2017-01-25 19:27 UTC
Windows 7
Maya 2017 - PySide 2

I'm seeing a couple issues when attempting to toggle off an optional InstancePlugin that runs during the ValidatorOrder step. Seen in versions 0.7.2 and 0.7.4

1. If I click the white box to toggle the plugin off, I get this:
`# RuntimeWarning: Invalid return value in function QAbstractListModel.setData, expected bool, got NoneType., at line 64`
in pyblish_lite\view.py

Note: this RuntimeWarning only occurs once after a fresh load of Maya.

2. After toggling off the optional plugin (and getting the RuntimeWarning above), the plugin still runs during validation, except only one instance will fail validation, when normally 2 would fail in my test scene. So it seems to stop running after the first failing instance?

**Comment by tokejepsen** [comment] 2017-01-25 19:38
Is it possible to post the code for the validator? Or does it fail on any validator?

**Comment by mottosso** [comment] 2017-01-25 20:02
Thanks @derrickb, having a look at this as soon as possible.

@tokejepsen, would you have a moment to look at this? I'm out of the country for a few weeks.

**Comment by mottosso** [comment] 2017-01-25 20:03
Ah, just saw you had already commented  :)

**Comment by derrickb** [comment] 2017-01-26 00:12
I did some more testing and I am now fairly certain that this is limited to the first optional validator as seen in the GUI's list:
![image](https://cloud.githubusercontent.com/assets/1793769/22310487/4c5351f8-e304-11e6-9afa-9384d469138c.png)

Notice how even though my "NonManifoldGeo" plugin is turned off, the first pSphere1 mesh still passes.  Before, my "UnshadedFaces" plugin was first in the list.  pShere1 is expected to fail this validator (I can't post its full code as it is not mine), and indeed it does fail even though the plugin is turned off.

![image](https://cloud.githubusercontent.com/assets/1793769/22314977/fa2407f0-e318-11e6-890e-21b42837d093.png)

**Comment by tokejepsen** [comment] 2017-01-26 08:46
What order is your validators?

**Comment by mottosso** [comment] 2017-01-26 14:54
Thanks @derrickb, I think the problem is related to #59.

The solution I have in mind involves removing the ability to pause and continue an ongoing publish. It's a rather complex feature and I haven't yet come across any feasible alternative solution to.

**Comment by derrickb** [comment] 2017-01-26 20:24
@tokejepsen I'm using `order = pyblish.api.ValidatorOrder`

@mottosso thanks for the reply, hope it's something that can get resolved soon. I'm going to try having a dummy plugin as the first in the list to see if I can use the rest as intended.

**Comment by mottosso** [comment] 2017-02-13 08:15
Closing this, it will be resolved alongside #59.

**Closed by mottosso** 2017-02-13 08:15 UTC
